### ISSUE TITLE
Upgrade to Python3 and Hy 0.14

### ISSUE THREAD

**Issue by gilch** [hylang/tryhy#6]
Hy got a new release last week. Python 2 support is legacy only and will be removed in a future version of Hy, so we should update that too at https://try-hy.appspot.com/

**Comment by proppy** [comment]
Sorry for the late reply, I didn't get notification from this repo.

@Kodiologist can you try out #7?

**Comment by proppy** [comment]
Sorry for the late reply, I didn't get notification from this repo.

@Kodiologist can you try out #7?

**Comment by Kodiologist** [comment]
The update seems to work, so thanks for that, but I'm afraid that we'll need a Try Hy substitute we control so it can updated and customized in the future.

**Comment by proppy** [comment]
@Kodiologist happy to transfer / ownership of the domain project (if we can manage to do so).

Or we can simply deploy the code somewhere else.

**Comment by Kodiologist** [comment]
Great, could you look into some means of transferring ownership?

**Comment by proppy** [comment]
@Kodiologist do you want to keep the domain (`http://try-hy.appspot.com/`) if not, it might be easier just to create a new project on https://console.cloud.google.com/ and re-deploy it there.

**Comment by Kodiologist** [comment]
It's probably fine either way.

**Comment by proppy** [comment]
@Kodiologist happy to merge https://github.com/hylang/tryhy/pull/7 in the meantime and redeploy to http://try-hy.appspot.com/ if that helps.
